# Introduction to Scikit-Learn (SK learn)

In [1]:
import pandas as pd
import numpy as np

In [2]:
hd = pd.read_csv("heart-disease.csv")
hd.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
#1. setting up the features (X) and labels (y)

X = hd.drop("target", axis=1)
y = hd["target"]

In [4]:
#2. choose the model and hyperparameters

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

In [5]:
# hyperparameters - initially we will consider using hyperparameters
# default values.

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [6]:
#3. Fit the model to the training data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
clf.fit(X_train, y_train);

In [8]:
# Making prediction about heart disease.

y_preds = clf.predict(X_test)
y_preds

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1])

In [9]:
y_test

157    1
280    0
21     1
102    1
95     1
      ..
242    0
141    1
32     1
225    0
89     1
Name: target, Length: 61, dtype: int64

In [10]:
#4. Evluate the model (how good the predictions are)


clf.score(X_train, y_train)

1.0

In [11]:
clf.score (X_test, y_test)

0.8032786885245902

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [13]:
print (classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.84      0.72      0.78        29
           1       0.78      0.88      0.82        32

    accuracy                           0.80        61
   macro avg       0.81      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61

In [14]:
confusion_matrix(y_test, y_preds)

array([[21,  8],
       [ 4, 28]])

In [15]:
accuracy_score(y_test, y_preds)

0.8032786885245902

In [16]:
#5. imporve a model (trying to change hyper parameters)

np.random.seed(23)

for i in range (10, 100, 10):
    print(f"Trying model with {i} estimators")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test data: {clf. score(X_test, y_test)*100:2f}")
    print("")

Trying model with 10 estimators
Model accuracy on test data: 70.491803

Trying model with 20 estimators
Model accuracy on test data: 80.327869

Trying model with 30 estimators
Model accuracy on test data: 81.967213

Trying model with 40 estimators
Model accuracy on test data: 83.606557

Trying model with 50 estimators
Model accuracy on test data: 81.967213

Trying model with 60 estimators
Model accuracy on test data: 80.327869

Trying model with 70 estimators
Model accuracy on test data: 81.967213

Trying model with 80 estimators
Model accuracy on test data: 80.327869

Trying model with 90 estimators
Model accuracy on test data: 83.606557

In [17]:
#6. save model and load it
import pickle

pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))

In [18]:
model = pickle.load(open("random_forest_model_1.pkl", "rb"))

In [19]:
model.score(X_test, y_test)

0.8360655737704918

## 01. GETTING THE DATA READY

Three step process
* Split the data into features and labels
* `Imputing`: Filling data or deleting missing values
* `Feature Encoding`: converting non-numerical values to numeric values

In [20]:

hd.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [21]:
X = hd.drop("target", axis=1)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [22]:
y = hd["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [23]:
# splitting the data into test and training data

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [24]:
X_train.shape, y_train.shape

((242, 13), (242,))

### 1.1 Making the data numerical

In [25]:
car_sales = pd.read_csv("extended_car_sales.csv")
car_sales.shape

(1000, 5)

In [26]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [27]:
car_sales.dtypes

Make                 str
Colour               str
Odometer (KM)    float64
Doors            float64
Price            float64
dtype: object

In [28]:
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [30]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Toyota'

In [1]:
# Turn the categories into numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                               remainder="passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

NameError: name 'X' is not defined

In [ ]:
pd.DataFrame(transformed_X)

In [ ]:
transformed_df = pd.DataFrame(
    transformed_X.toarray(),
    columns=transformer.get_feature_names_out()
)

transformed_df.head()

In [ ]:
transformed_X = transformed_X.toarray()
df = pd.DataFrame(transformed_X)
df.head()

In [ ]:
car_sales.head()

In [ ]:
np.random.seed(12)

X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, train_size=0.2)
model.fit(X_train, y_train)

## Handling Missing values
* `Imputation` - filling values with some data
* Removing the records all togather

In [ ]:
car_sales.isna().sum()

### 1: using pandas to fill values

In [ ]:
car_sales["Make"].fillna("missing", inplace=True)
car_sales["Colour"].fillna("missing", inplace=True)
car_sales["Odometer (KM)"].fillna(car_sales["Odometer (KM)"].mean(), inplace=True)
car_sales["Doors"].fillna(4, inplace=True)

In [ ]:
car_sales.isna().sum()

In [ ]:
car_sales.dropna(inplace=True)

In [ ]:
car_sales.isna().sum()

In [ ]:
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

In [ ]:
# Turn the categories into numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                               remainder="passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, train_size=0.2)
model.fit(X_train, y_train);

In [ ]:
model.score(X_test, y_test)

### 2. Filling values using ScikitLearn

In [ ]:
car_sales_new = pd.read_csv("extended_car_sales.csv")
car_sales_new.isna().sum()

In [ ]:
car_sales_new.dropna(subset=["Price"], inplace=True)
car_sales_new.isna().sum()

In [ ]:
X = car_sales_new.drop("Price", axis=1)
y = car_sales_new["Price"]

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Define Strategy
category_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# Define Columns/categories/features
category_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

# create an imputer
imputer = ColumnTransformer([
    ("category_imputer", category_imputer, category_features),
    ("door_imputer", door_imputer, door_features),
    ("num_imputer", num_imputer, num_features)
])

# Transform the data
filled_X = imputer.fit_transform(X)
filled_X

In [ ]:
car_sales_filled=pd.DataFrame(filled_X,
            columns=["Make", "Colour", "Doors", "Odometer (KM)"])

In [ ]:
car_sales_filled

In [ ]:
car_sales_filled.isna().sum()

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  category_features)],
                                remainder="passthrough")

transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

In [ ]:
# Turn the categories into numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                               remainder="passthrough")
transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

# 2. Choosing the right Estimator/Model
1. Classification - predicting whether a sample is one thing or another.
2. Regression - predicting a number

In [31]:
from sklearn.datasets import fetch_california_housing
california = fetch_california_housing()
california

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [32]:
california_df = pd.DataFrame(california["data"], columns=california["feature_names"])
california_df["target"] = pd.Series(california["target"])

california_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [33]:
california_df.shape

(20640, 9)

In [34]:
from sklearn.linear_model import Ridge

X = california_df.drop("target", axis=1)
y = california_df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = Ridge()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.5891023797560013

In [ ]:
from sklearn.ensemble import RandomForestRegressor

X = california_df.drop("target", axis=1)
y = california_df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

rf = RandomForestRegressor()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

# 3. Fit the model to the data

In [35]:
heart_disease = pd.read_csv("heart-disease.csv")

np.random.seed(22)
from sklearn.ensemble import RandomForestClassifier

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2)

clf = RandomForestClassifier()

# fitting the model to the data.
clf.fit(X_train, y_train)

clf.score(X_test, y_test)

0.8024691358024691

### 3.1 Making predictions using a machine learning model
1. `predict()` function
2. `predict_proba()` function

In [36]:
clf.predict(X_test)

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1])

In [37]:
np.array(y_test)

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1])

In [38]:
# comparing predictions with the real values

y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

np.float64(0.8024691358024691)

In [39]:
clf.score(X_test, y_test)

0.8024691358024691

In [40]:
# using predict_proba()
clf.predict_proba(X_test[:5])

array([[0.48, 0.52],
       [0.09, 0.91],
       [0.21, 0.79],
       [0.67, 0.33],
       [0.01, 0.99]])

In [41]:
clf.predict(X_test[:5])

array([1, 1, 1, 0, 1])

In [43]:
# predict for regression

from sklearn.ensemble import RandomForestRegressor

X=california_df.drop("target", axis=1)
y=california_df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(X_test, y_test)

y_preds = model.predict(X_test)
y_preds[:5]

array([0.82121  , 4.8496184, 0.84353  , 1.86489  , 3.14407  ])

In [44]:
np.array(y_test[:5])

array([0.675  , 5.00001, 0.827  , 1.857  , 3.294  ])

In [45]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

0.14059326581879883

### Evaluating a Model
* score method
* scoring parameter
* problem-specific metric functions

In [46]:
# scoring parameter

from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

np.random.seed(23)

X = hd.drop("target", axis=1)
y = hd["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train);

In [47]:
model.score(X_test, y_test)

0.8032786885245902

In [49]:
cross_val_score(model, X, y, cv = 10)

array([0.90322581, 0.80645161, 0.87096774, 0.86666667, 0.86666667,
       0.86666667, 0.73333333, 0.86666667, 0.73333333, 0.76666667])

In [ ]:
from IPython.display import Image
Image(filename='cross_val.png')

In [ ]:
single_score = model.score(X_test, y_test)
cross_score = np.mean(cross_val_score(model, X, y)) # try cv=10

single_score, cross_score

1. accuracy
2. area under ROC curve
3. confusion metric
4. classification report

### Area under the receiver operating characteristic curve
POC shows comparison of models tpr vs fpr

- tpr = model predicts 1 when truth is 1
- fpr = model predicts 1 when truth is 0
- tnr = model predicts 0 when truth is 0
- fnr = model predicts 0 when truth is 1

In [ ]:
from sklearn.metrics import roc_curve
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2)

model.fit(X_train, y_train)

y_probs = clf.predict_proba(X_test)

y_probs[:10], len(y_probs)

In [ ]:
y_probs_positive = y_probs[:,1]
y_probs_positive[:10]

In [ ]:
fpr, tpr, thresholds = roc_curve(y_test, y_probs_positive)

fpr